name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: norelease
          use_github_release_notes: true

      - name: Log Release Version
        run: |
          echo "Created tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Created release version: ${{ steps.release.outputs.version }}"

      - name: Upload JS card file to release
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.version }}
          file: dist/lovelace-horizon-card.js
